### ISSUE TITLE
Create CODE-OF-CONDUCT.md file

### ISSUE THREAD

**Issue by Sitanshu-AI** [Learn-Write-Repeat/LWR-WebApp#5] opened 2021-07-10 22:49 UTC
i would like to create code of conduct file

**Comment by dhwaj1902** [comment] 2021-07-11 16:43
Ok @Sitanshu-AI Go Ahead

**Comment by swathi-469** [comment] 2021-07-12 05:22
If the issue is open , please assign this to me, I am ready with my work

**Comment by dhwaj1902** [comment] 2021-07-12 05:24
@swathi-469 sorry but there is already a PR raised by @Sitanshu-AI regarding this issue.

**Closed as completed** 2021-07-12 05:48 UTC
Labels: documentation, 🟪 Level0, DCP21
